package controllers;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class VentanaMetodoVentaController {

	// Event Listener on Button.onAction
	@FXML
	public void ueps(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void pesoPromedio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void peps(ActionEvent event) {
		// TODO Autogenerated
	}
}
